services:
  postgres:
    image: postgres:16-alpine
    container_name: luftborn-postgres
    environment:
      POSTGRES_DB: luftborn_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - luftborn-network

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: luftborn-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=luftborn_db;Username=postgres;Password=postgres
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - luftborn-network
    volumes:
      - ./src/backend/Luftborn.Api/logs:/app/logs

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: luftborn-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - luftborn-network

volumes:
  postgres_data:


networks:
  luftborn-network:
    driver: bridge
